/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 16.0.6 -fPIC -Os) */

module gf180mcu_fd_sc_mcu7t5v0__addf_1(S, A, CI, B, CO, VDD, VSS, VNW, VPW);
  input A;
  wire A;
  input B;
  wire B;
  input CI;
  wire CI;
  output CO;
  wire CO;
  output S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__addf_2(S, A, CI, B, CO, VDD, VSS, VNW, VPW);
  input A;
  wire A;
  input B;
  wire B;
  input CI;
  wire CI;
  output CO;
  wire CO;
  output S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__addf_4(S, A, CI, B, CO, VDD, VSS, VNW, VPW);
  input A;
  wire A;
  input B;
  wire B;
  input CI;
  wire CI;
  output CO;
  wire CO;
  output S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__addf_func(S, A, CI, B, CO, VDD, VSS, VNW, VPW);
  input A;
  wire A;
  input B;
  wire B;
  input CI;
  wire CI;
  output CO;
  wire CO;
  output S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__addh_1(CO, A, B, S, VDD, VSS, VNW, VPW);
  input A;
  wire A;
  input B;
  wire B;
  output CO;
  wire CO;
  output S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__addh_2(CO, A, B, S, VDD, VSS, VNW, VPW);
  input A;
  wire A;
  input B;
  wire B;
  output CO;
  wire CO;
  output S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__addh_4(A, B, CO, S, VDD, VSS, VNW, VPW);
  input A;
  wire A;
  input B;
  wire B;
  output CO;
  wire CO;
  output S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__addh_func(CO, A, B, S, VDD, VSS, VNW, VPW);
  input A;
  wire A;
  input B;
  wire B;
  output CO;
  wire CO;
  output S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and2_1(A1, A2, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and2_2(A1, A2, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and2_4(A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and2_func(A1, A2, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and3_1(A1, A2, A3, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and3_2(A1, A2, A3, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and3_4(A3, A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and3_func(A3, A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and4_1(A1, A2, A3, A4, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and4_2(A1, A2, A3, A4, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and4_4(A4, A3, A1, A2, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__and4_func(A1, A2, A3, A4, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__antenna(I, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__antenna_func(I, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi211_1(A2, ZN, A1, B, C, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi211_2(A2, A1, ZN, B, C, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi211_4(ZN, A2, A1, B, C, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi211_func(ZN, A2, A1, B, C, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi21_1(A2, ZN, A1, B, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi21_2(B, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi21_4(A2, A1, ZN, B, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi21_func(A2, A1, ZN, B, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi221_1(B2, B1, ZN, C, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi221_2(ZN, B2, C, B1, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi221_4(ZN, B2, B1, C, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi221_func(B2, B1, ZN, C, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi222_1(C2, C1, B1, ZN, B2, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  input C2;
  wire C2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi222_2(ZN, C2, C1, B2, B1, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  input C2;
  wire C2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi222_4(ZN, C2, C1, B1, B2, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  input C2;
  wire C2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi222_func(ZN, C2, C1, B1, B2, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  input C2;
  wire C2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi22_1(B2, B1, ZN, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi22_2(B2, B1, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi22_4(B2, B1, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__aoi22_func(B2, B1, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__buf_1(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__buf_12(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__buf_16(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__buf_2(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__buf_20(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__buf_3(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__buf_4(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__buf_8(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__buf_func(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__bufz_1(EN, I, Z, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__bufz_12(EN, I, Z, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__bufz_16(EN, I, Z, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__bufz_2(EN, I, Z, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__bufz_3(EN, I, Z, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__bufz_4(EN, I, Z, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__bufz_8(EN, I, Z, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__bufz_func(EN, I, Z, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkbuf_1(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkbuf_12(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkbuf_16(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkbuf_2(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkbuf_20(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkbuf_3(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkbuf_4(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkbuf_8(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkbuf_func(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkinv_1(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkinv_12(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkinv_16(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkinv_2(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkinv_20(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkinv_3(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkinv_4(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkinv_8(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__clkinv_func(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnq_1(CLKN, D, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnq_2(CLKN, D, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnq_4(CLKN, D, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnq_func(CLKN, D, Q, VDD, VSS, VNW, VPW, notifier);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnrnq_1(CLKN, D, RN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnrnq_2(CLKN, D, RN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnrnq_4(CLKN, D, RN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnrnq_func(CLKN, D, RN, Q, VDD, VSS, VNW, VPW, notifier);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnrsnq_1(CLKN, D, SETN, RN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnrsnq_2(CLKN, D, SETN, RN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnrsnq_4(CLKN, D, SETN, RN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnrsnq_func(CLKN, D, SETN, RN, Q, VDD, VSS, VNW, VPW, notifier);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnsnq_1(CLKN, D, SETN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnsnq_2(CLKN, D, SETN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnsnq_4(CLKN, D, SETN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffnsnq_func(CLKN, D, SETN, Q, VDD, VSS, VNW, VPW, notifier);
  input CLKN;
  wire CLKN;
  input D;
  wire D;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffq_1(CLK, D, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffq_2(CLK, D, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffq_4(CLK, D, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffq_func(CLK, D, Q, VDD, VSS, VNW, VPW, notifier);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffrnq_1(CLK, D, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffrnq_2(CLK, D, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffrnq_4(CLK, D, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffrnq_func(CLK, D, RN, Q, VDD, VSS, VNW, VPW, notifier);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffrsnq_1(CLK, D, SETN, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffrsnq_2(CLK, D, SETN, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffrsnq_4(CLK, D, SETN, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffrsnq_func(CLK, D, SETN, RN, Q, VDD, VSS, VNW, VPW, notifier);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffsnq_1(CLK, D, SETN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffsnq_2(CLK, D, SETN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffsnq_4(CLK, D, SETN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dffsnq_func(CLK, D, SETN, Q, VDD, VSS, VNW, VPW, notifier);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlya_1(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlya_2(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlya_4(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlya_func(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyb_1(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyb_2(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyb_4(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyb_func(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyc_1(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyc_2(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyc_4(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyc_func(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyd_1(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyd_2(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyd_4(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__dlyd_func(I, Z, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__endcap(VDD, VSS);
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__endcap_func(VDD, VSS);
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fill_1(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fill_16(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fill_2(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fill_32(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fill_4(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fill_64(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fill_8(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fill_func(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fillcap_16(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fillcap_32(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fillcap_4(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fillcap_64(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fillcap_8(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__fillcap_func(VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__filltie(VDD, VSS);
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__filltie_func(VDD, VSS);
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__hold(Z, VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  inout Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__hold_func(Z, VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  inout Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__icgtn_1(TE, E, CLKN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input E;
  wire E;
  output Q;
  wire Q;
  input TE;
  wire TE;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__icgtn_2(TE, E, CLKN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input E;
  wire E;
  output Q;
  wire Q;
  input TE;
  wire TE;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__icgtn_4(TE, E, CLKN, Q, VDD, VSS, VNW, VPW);
  input CLKN;
  wire CLKN;
  input E;
  wire E;
  output Q;
  wire Q;
  input TE;
  wire TE;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__icgtn_func(TE, E, CLKN, Q, VDD, VSS, VNW, VPW, notifier);
  input CLKN;
  wire CLKN;
  input E;
  wire E;
  output Q;
  wire Q;
  input TE;
  wire TE;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__icgtp_1(TE, E, CLK, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input E;
  wire E;
  output Q;
  wire Q;
  input TE;
  wire TE;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__icgtp_2(TE, E, CLK, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input E;
  wire E;
  output Q;
  wire Q;
  input TE;
  wire TE;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__icgtp_4(TE, E, CLK, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input E;
  wire E;
  output Q;
  wire Q;
  input TE;
  wire TE;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__icgtp_func(TE, E, CLK, Q, VDD, VSS, VNW, VPW, notifier);
  input CLK;
  wire CLK;
  input E;
  wire E;
  output Q;
  wire Q;
  input TE;
  wire TE;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__inv_1(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__inv_12(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__inv_16(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__inv_2(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__inv_20(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__inv_3(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__inv_4(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__inv_8(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__inv_func(I, ZN, VDD, VSS, VNW, VPW);
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__invz_1(EN, ZN, I, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__invz_12(EN, I, ZN, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__invz_16(EN, I, ZN, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__invz_2(EN, ZN, I, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__invz_3(EN, I, ZN, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__invz_4(EN, I, ZN, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__invz_8(EN, I, ZN, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__invz_func(EN, ZN, I, VDD, VSS, VNW, VPW);
  input EN;
  wire EN;
  input I;
  wire I;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latq_1(E, D, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latq_2(E, D, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latq_4(E, D, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latq_func(E, D, Q, VDD, VSS, VNW, VPW, notifier);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latrnq_1(E, D, RN, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latrnq_2(E, D, RN, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latrnq_4(E, D, RN, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latrnq_func(E, D, RN, Q, VDD, VSS, VNW, VPW, notifier);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input RN;
  wire RN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latrsnq_1(E, D, RN, SETN, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latrsnq_2(E, D, RN, SETN, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latrsnq_4(E, D, RN, SETN, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latrsnq_func(E, D, RN, SETN, Q, VDD, VSS, VNW, VPW, notifier);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latsnq_1(E, D, SETN, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latsnq_2(E, D, SETN, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latsnq_4(E, D, SETN, Q, VDD, VSS, VNW, VPW);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__latsnq_func(E, D, SETN, Q, VDD, VSS, VNW, VPW, notifier);
  input D;
  wire D;
  input E;
  wire E;
  output Q;
  wire Q;
  input SETN;
  wire SETN;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__mux2_1(Z, I1, S, I0, VDD, VSS, VNW, VPW);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__mux2_2(Z, I1, S, I0, VDD, VSS, VNW, VPW);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__mux2_4(Z, I1, S, I0, VDD, VSS, VNW, VPW);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__mux2_func(Z, I1, S, I0, VDD, VSS, VNW, VPW);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input S;
  wire S;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__mux4_1(I2, S0, I3, Z, S1, I1, I0, VDD, VSS, VNW, VPW);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input S0;
  wire S0;
  input S1;
  wire S1;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__mux4_2(I2, S0, I3, Z, S1, I1, I0, VDD, VSS, VNW, VPW);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input S0;
  wire S0;
  input S1;
  wire S1;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__mux4_4(I2, S0, I3, Z, S1, I1, I0, VDD, VSS, VNW, VPW);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input S0;
  wire S0;
  input S1;
  wire S1;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__mux4_func(I2, S0, I3, Z, S1, I1, I0, VDD, VSS, VNW, VPW);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input S0;
  wire S0;
  input S1;
  wire S1;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand2_1(A2, A1, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand2_2(A1, A2, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand2_4(A1, A2, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand2_func(A1, A2, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand3_1(A3, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand3_2(ZN, A3, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand3_4(A2, ZN, A3, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand3_func(ZN, A3, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand4_1(A4, ZN, A3, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand4_2(ZN, A3, A1, A4, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand4_4(A3, ZN, A4, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nand4_func(A3, ZN, A4, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor2_1(A2, ZN, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor2_2(A2, ZN, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor2_4(ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor2_func(ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor3_1(A3, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor3_2(ZN, A3, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor3_4(A2, ZN, A3, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor3_func(A2, ZN, A3, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor4_1(A4, ZN, A3, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor4_2(A4, A3, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor4_4(A4, A3, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__nor4_func(A4, A3, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai211_1(A2, ZN, A1, B, C, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai211_2(A2, ZN, A1, B, C, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai211_4(A2, ZN, A1, B, C, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai211_func(A2, ZN, A1, B, C, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai21_1(A2, ZN, A1, B, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai21_2(B, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai21_4(A2, ZN, A1, B, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai21_func(A2, ZN, A1, B, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai221_1(B2, B1, C, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai221_2(B2, B1, ZN, C, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai221_4(ZN, B1, B2, C, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai221_func(B2, B1, C, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C;
  wire C;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai222_1(C2, C1, B1, ZN, B2, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  input C2;
  wire C2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai222_2(ZN, C1, C2, B1, B2, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  input C2;
  wire C2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai222_4(C1, ZN, C2, B1, B2, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  input C2;
  wire C2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai222_func(C1, ZN, C2, B1, B2, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  input C2;
  wire C2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai22_1(B2, B1, ZN, A1, A2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai22_2(B2, B1, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai22_4(B2, B1, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai22_func(B2, B1, ZN, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai31_1(B, A1, ZN, A2, A3, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai31_2(B, ZN, A3, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai31_4(A3, ZN, A1, A2, B, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai31_func(A3, ZN, A1, A2, B, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B;
  wire B;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai32_1(A3, A2, A1, ZN, B1, B2, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai32_2(A3, A2, A1, ZN, B2, B1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai32_4(A2, A3, A1, ZN, B2, B1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai32_func(A2, A3, A1, ZN, B2, B1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai33_1(B3, B2, B1, ZN, A1, A2, A3, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input B3;
  wire B3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai33_2(B3, B2, ZN, B1, A3, A2, A1, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input B3;
  wire B3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai33_4(B2, B3, B1, ZN, A1, A2, A3, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input B3;
  wire B3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__oai33_func(B3, B2, B1, ZN, A1, A2, A3, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input B3;
  wire B3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or2_1(A1, A2, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or2_2(A1, A2, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or2_4(A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or2_func(A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or3_1(A1, A2, A3, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or3_2(A1, A2, A3, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or3_4(A3, A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or3_func(A1, A2, A3, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or4_1(A1, A2, A3, A4, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or4_2(A1, A2, A3, A4, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or4_4(A4, A3, A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__or4_func(A1, A2, A3, A4, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffq_1(SE, SI, D, CLK, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SE;
  wire SE;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffq_2(SE, SI, D, CLK, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SE;
  wire SE;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffq_4(SE, SI, D, CLK, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SE;
  wire SE;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffq_func(SE, SI, D, CLK, Q, VDD, VSS, VNW, VPW, notifier);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SE;
  wire SE;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffrnq_1(SE, SI, D, CLK, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SE;
  wire SE;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffrnq_2(SE, SI, D, CLK, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SE;
  wire SE;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffrnq_4(SE, SI, D, CLK, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SE;
  wire SE;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffrnq_func(SE, SI, D, CLK, RN, Q, VDD, VSS, VNW, VPW, notifier);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SE;
  wire SE;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffrsnq_1(SE, SI, D, CLK, SETN, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SE;
  wire SE;
  input SETN;
  wire SETN;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffrsnq_2(SE, SI, D, CLK, SETN, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SE;
  wire SE;
  input SETN;
  wire SETN;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffrsnq_4(SE, SI, D, CLK, SETN, RN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SE;
  wire SE;
  input SETN;
  wire SETN;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffrsnq_func(SE, SI, D, CLK, SETN, RN, Q, VDD, VSS, VNW, VPW, notifier);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RN;
  wire RN;
  input SE;
  wire SE;
  input SETN;
  wire SETN;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffsnq_1(SE, SI, D, CLK, SETN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SE;
  wire SE;
  input SETN;
  wire SETN;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffsnq_2(SE, SI, D, CLK, SETN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SE;
  wire SE;
  input SETN;
  wire SETN;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffsnq_4(SE, SI, D, CLK, SETN, Q, VDD, VSS, VNW, VPW);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SE;
  wire SE;
  input SETN;
  wire SETN;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__sdffsnq_func(SE, SI, D, CLK, SETN, Q, VDD, VSS, VNW, VPW, notifier);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SE;
  wire SE;
  input SETN;
  wire SETN;
  input SI;
  wire SI;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  input notifier;
  wire notifier;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__tieh(Z, VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__tieh_func(Z, VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__tiel(ZN, VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__tiel_func(ZN, VDD, VSS, VNW, VPW);
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xnor2_1(A2, A1, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xnor2_2(A2, A1, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xnor2_4(A2, A1, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xnor2_func(A2, A1, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xnor3_1(A2, A1, A3, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xnor3_2(A2, A1, A3, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xnor3_4(A2, A1, A3, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xnor3_func(A2, A1, A3, ZN, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output ZN;
  wire ZN;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xor2_1(A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xor2_2(A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xor2_4(A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xor2_func(A2, A1, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xor3_1(A2, A1, A3, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xor3_2(A2, A1, A3, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xor3_4(A2, A1, A3, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule

module gf180mcu_fd_sc_mcu7t5v0__xor3_func(A2, A1, A3, Z, VDD, VSS, VNW, VPW);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  inout VDD;
  wire VDD;
  inout VNW;
  wire VNW;
  inout VPW;
  wire VPW;
  inout VSS;
  wire VSS;
  output Z;
  wire Z;
endmodule
